'use client';

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Clock, Zap } from 'lucide-react';

interface SummaryPanelProps {
  closedSummary: string;
  openSummary: string;
  closedModel: string;
  openModel: string;
  isLoading?: boolean;
}

export default function SummaryPanel({
  closedSummary,
  openSummary,
  closedModel,
  openModel,
  isLoading = false
}: SummaryPanelProps) {
  if (isLoading) {
    return (
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              🔒 Closed-Source Summary
              <Badge variant="secondary">
                <Clock className="h-3 w-3 mr-1" />
                Generating...
              </Badge>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="animate-pulse space-y-3">
              <div className="h-4 bg-muted rounded w-full"></div>
              <div className="h-4 bg-muted rounded w-5/6"></div>
              <div className="h-4 bg-muted rounded w-4/6"></div>
              <div className="h-4 bg-muted rounded w-full"></div>
              <div className="h-4 bg-muted rounded w-3/4"></div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              🌐 Open-Source Summary
              <Badge variant="secondary">
                <Clock className="h-3 w-3 mr-1" />
                Generating...
              </Badge>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="animate-pulse space-y-3">
              <div className="h-4 bg-muted rounded w-full"></div>
              <div className="h-4 bg-muted rounded w-5/6"></div>
              <div className="h-4 bg-muted rounded w-4/6"></div>
              <div className="h-4 bg-muted rounded w-full"></div>
              <div className="h-4 bg-muted rounded w-3/4"></div>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  if (!closedSummary && !openSummary) {
    return (
      <Card className="text-center py-12">
        <CardContent>
          <div className="space-y-4">
            <Zap className="h-12 w-12 mx-auto text-muted-foreground" />
            <div>
              <h3 className="text-lg font-semibold">Ready to Compare</h3>
              <p className="text-muted-foreground">
                Select your models and input text to see the summarization showdown!
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
      <Card className="border-l-4 border-l-blue-500">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            🔒 Closed-Source Summary
          </CardTitle>
          <CardDescription>
            Generated by {closedModel?.toUpperCase() || 'Unknown Model'}
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="prose prose-sm max-w-none">
            <p className="text-sm leading-relaxed whitespace-pre-wrap">
              {closedSummary || 'No summary generated yet.'}
            </p>
          </div>
          {closedSummary && (
            <div className="mt-4 pt-4 border-t">
              <div className="flex items-center gap-4 text-xs text-muted-foreground">
                <span>{closedSummary.length} characters</span>
                <span>{closedSummary.split(' ').length} words</span>
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      <Card className="border-l-4 border-l-green-500">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            🌐 Open-Source Summary
          </CardTitle>
          <CardDescription>
            Generated by {openModel?.replace('-', ' ').toUpperCase() || 'Unknown Model'}
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="prose prose-sm max-w-none">
            <p className="text-sm leading-relaxed whitespace-pre-wrap">
              {openSummary || 'No summary generated yet.'}
            </p>
          </div>
          {openSummary && (
            <div className="mt-4 pt-4 border-t">
              <div className="flex items-center gap-4 text-xs text-muted-foreground">
                <span>{openSummary.length} characters</span>
                <span>{openSummary.split(' ').length} words</span>
              </div>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
} 
 